---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull thugrock/calculator:latest
    - name: run docker image
      shell: docker run -v "/etc/docker_logs/test.log":"/src/app/test.log" -v "/etc/docker_logs/flask.log":"/src/app/falsk.log" -p 3000:3000 -d --rm thugrock/calculator
    - name: Test the application
      shell: python3 test_app.py
