---
- name: Clean previous versions of Calculator
  hosts: all
  tasks:
    - name: clean docker containers
      shell: docker rm -f $(docker ps --filter expose=13962 -q)
    - name: clean docker images
      shell: docker rmi -f $(docker images --filter "dangling=true" -q --no-trunc)
